#' Generate a traceback from a list of calls.
#' 
#' @param callstack stack of calls, as generated by (e.g.) 
#'   \code{\link[base]{sys.calls}}
#' @keywords internal
#' @export
create_traceback <- function(callstack) {
  calls <- lapply(callstack, deparse, width = 500)
  calls <- sapply(calls, str_c, collapse = "\n")
  first_eval <- match("eval(expr, envir, enclos)", calls, 0)[1]
  
  if (first_eval == length(calls)) return()
  
  user_calls <- calls[-seq_len(first_eval)]
  user_calls <- str_c(seq_along(user_calls), ": ", user_calls, sep = "")
  user_calls <- str_replace(user_calls, "\n", "\n   ")
  user_calls 
}

#' Try, capture stack on error.
#'
#' This is a variant of \code{\link{tryCatch}} that also captures the call
#' stack if an error occurs.
#'
#' @param quoted_code code to evaluate, in quoted form
#' @param env environment in which to execute code
#' @keywords internal
#' @export
try_capture_stack <- function(quoted_code, env) {
  capture_calls <- function(e) {
    # Capture call stack, removing last two calls, which are added by
    # withCallingHandlers
    e$calls <- head(sys.calls(), -2)
    signalCondition(e)
  }
  
  tryCatch(
    withCallingHandlers(eval(quoted_code, env), error = capture_calls),
    error = identity
  )
}